#+TITLE: My emacs init file!
#+AUTHOR: BELAID Mohammed Said
#+EMAIL: said.belaid@univ-usto.dz

* Try
  Helps trying new packages w/o installing them!
  #+BEGIN_SRC emacs-lisp    
    (use-package try
      :ensure t)
  #+END_SRC
* Interface / Themes
** Main theme
   Was using tango, tandotango... for now zenburn is the best
   #+BEGIN_SRC emacs-lisp
     ;;(load-theme 'tango-dark)
     (use-package zenburn-theme
       :ensure t
       :config (load-theme 'zenburn t))
   #+END_SRC
** Add some awesome transparency ;)
   #+BEGIN_SRC emacs-lisp
     (set-frame-parameter (selected-frame) 'alpha '(95 . 95))
     (add-to-list 'default-frame-alist '(alpha . (95 . 95)))
   #+END_SRC
** No action bars
   #+BEGIN_SRC emacs-lisp
     (menu-bar-mode -1)
     (tool-bar-mode -1)
     (toggle-scroll-bar -1)
   #+END_SRC
** Highlight current line
   #+BEGIN_SRC emacs-lisp
     (global-hl-line-mode t)
     ;; and change the default color!
     (set-face-background 'hl-line "#3e4446")
     (set-face-foreground 'highlight nil)
   #+END_SRC
** Beacon
   Flashes the cursor line when moving the point (from a window to another, or when scrolling)
   #+BEGIN_SRC emacs-lisp
     (use-package beacon
       :ensure t
       :config
       (beacon-mode 1))
   #+END_SRC
** Shrink/Enlarge Windows
   #+BEGIN_SRC emacs-lisp
     (global-set-key (kbd "S-C-<left>") 'shrink-window-horizontally)
     (global-set-key (kbd "S-C-<right>") 'enlarge-window-horizontally)
     (global-set-key (kbd "S-C-<down>") 'shrink-window)
     (global-set-key (kbd "S-C-<up>") 'enlarge-window)
   #+END_SRC
** Golden ration for multiple windows
   #+BEGIN_SRC emacs-lisp
     (use-package golden-ratio
       :ensure t
       :init (golden-ratio-mode 1))
   #+END_SRC
** A nice writing environment
   #+BEGIN_SRC emacs-lisp
     (use-package olivetti
       :ensure t)
   #+END_SRC
** TODO Highlight indentation
* Helpers
** Which key
   #+BEGIN_SRC emacs-lisp
     (use-package which-key
       :ensure t
       :config (which-key-mode))
   #+END_SRC
** Y/N instead of Yes/No
   #+BEGIN_SRC emacs-lisp
     (fset 'yes-or-no-p 'y-or-n-p)
   #+END_SRC
* Auto-complete / Ckeck
** MiniBuffer
   #+BEGIN_SRC emacs-lisp
     (use-package counsel
       :ensure t
       :bind
       (("M-y" . counsel-yank-pop)
        :map ivy-minibuffer-map
        ("M-y" . ivy-next-line)))

     (use-package ivy
       :ensure t
       :diminish (ivy-mode)
       :bind (("C-x b" . ivy-switch-buffer))
       :config
       (ivy-mode 1)
       (setq ivy-use-virtual-buffers t)
       (setq ivy-count-format "%d/%d ")
       (setq ivy-display-style 'fancy))

     (use-package swiper
       :ensure t
       :bind (("C-s" . swiper-isearch)
              ("C-r" . swiper-isearch)
              ("C-c C-r" . ivy-resume)
              ("M-x" . counsel-M-x)
              ("C-x C-f" . counsel-find-file))
       :config
       (progn
         (ivy-mode 1)
         (setq ivy-use-virtual-buffers t)
         (setq ivy-display-style 'fancy)
         (define-key read-expression-map (kbd "C-r") 'counsel-expression-history)
         ))
   #+END_SRC
** Global
   #+BEGIN_SRC emacs-lisp
     (use-package auto-complete
       :ensure t
       :init
       (progn
         (ac-config-default)
         (global-auto-complete-mode t)
         ))
   #+END_SRC
** Yasnippet
   A template system for programming languages
   #+BEGIN_SRC emacs-lisp
     (use-package yasnippet
       :ensure t
       :config (yas-global-mode 1))
   #+END_SRC
** TODO Abbreviation
   #+BEGIN_SRC emacs-lisp
   
   #+END_SRC
** 
* Checkers
** Flycheck
   #+BEGIN_SRC emacs-lisp
     (use-package flycheck
       :ensure t
       :init
       (global-flycheck-mode t)
       (add-hook 'after-init-hook #'global-flycheck-mode)
       (add-hook 'c++-mode-hook (lambda () (setq flycheck-gcc-language-standard "c++11")))
       )
   #+END_SRC
** TODO languagetool
   [[https://github.com/mhayashi1120/Emacs-langtool/][languagetool]]
* Editing
** Smart parentheses
   #+BEGIN_SRC emacs-lisp
     (use-package smartparens
       :ensure t
       :init
       (smartparens-global-mode))
   #+END_SRC
** Hungry delete
   #+BEGIN_SRC emacs-lisp
     (use-package hungry-delete
       :ensure t
       :config
       (global-hungry-delete-mode))
   #+END_SRC
** Write over a selection
   By default, emacs doesn't allow writing over a selected region
   #+BEGIN_SRC emacs-lisp
     (pending-delete-mode t)
   #+END_SRC
** Iedit
   Edit multiple similar regions at the same time using ~C-;~ 
   #+BEGIN_SRC emacs-lisp
     (use-package iedit
       :ensure t)
   #+END_SRC
** Expand region 
   This alows to select regions by expanding the selection ~C-=~
   #+BEGIN_SRC emacs-lisp
     (use-package expand-region
       :ensure t
       :config 
       (global-set-key (kbd "C-=") 'er/expand-region))
   #+END_SRC
* Org-mode
** Bullets
   #+BEGIN_SRC emacs-lisp
     (use-package org-bullets
       :ensure t)
     (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
   #+END_SRC
** Awesome code in org-mode
   Display code in org-mode with highlighting.
   #+BEGIN_SRC emacs-lisp
     (setq org-src-fontify-natively t)
   #+END_SRC
** Exportation
*** Reveal
    #+BEGIN_SRC emacs-lisp
      (use-package org-re-reveal
        :ensure t)
    #+END_SRC
**** TODO Install reveal.js
*** Bootstrap
    #+BEGIN_SRC emacs-lisp
      (use-package ox-twbs
        :ensure t)
    #+END_SRC
*** TODO Book
*** TODO HTML templates
** Babel
   Execute code in org-mode!
   #+BEGIN_SRC emacs-lisp
     (org-babel-do-load-languages
      'org-babel-load-languages
      '((gnuplot . t)
        (ditaa . t)
        (plantuml . t)
        (java . t)
        (shell . t)
        (C . t)))
   #+END_SRC
*** TODO Plantuml config / Install JDK
    #+BEGIN_SRC emacs-lisp
      (setq org-plantuml-jar-path (expand-file-name "~/.emacs.d/plantuml.jar"))
      ;; Do not promt for plantuml or ditaa
      (defun my-org-confirm-babel-evaluate (lang body)
        (not (or (string= lang "plantuml") (string= lang "ditaa"))))
      (setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
      ;; Display images after evaluation
      (add-hook 'org-babel-after-execute-hook 'org-display-inline-images 'append)
    #+END_SRC
*** Avoid ispelling source blocks
    #+BEGIN_SRC emacs-lisp
      (add-to-list 'ispell-skip-region-alist '("~" "~"))
      (add-to-list 'ispell-skip-region-alist '("=" "="))
      (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_SRC" . "^#\\+END_SRC"))
    #+END_SRC
*** 
** Agenda
* Versionning
** Magit
   #+BEGIN_SRC emacs-lisp
     (use-package  magit
       :ensure t)
     (global-set-key (kbd "C-x g") 'magit-status)
   #+END_SRC
* Misc
** Stop the annoying 'error' sound 
   #+BEGIN_SRC emacs-lisp
     (setq ring-bell-function 'ignore)
   #+END_SRC

